export const MIN_RECORDING_DURATION_SECONDS = 1;
export const VOICE_ENROLLMENT_TARGET_SECONDS = 15;
export const MAX_RECORDING_DURATION_SECONDS = 180;
export const MAX_RECORDING_SIZE_BYTES = 12 * 1024 * 1024;
export const MIN_RECORDING_SIZE_BYTES = 512;
