export const MIN_RECORDING_DURATION_SECONDS = 7;
export const VOICE_ENROLLMENT_TARGET_SECONDS = 15;
export const VOICE_ENROLLMENT_TARGET_MIN_SECONDS = 12;
export const VOICE_ENROLLMENT_TARGET_MAX_SECONDS = 20;
export const MAX_RECORDING_DURATION_SECONDS = 30;
export const MAX_RECORDING_SIZE_BYTES = 12 * 1024 * 1024;
export const MIN_RECORDING_SIZE_BYTES = 512;
