export const MIN_RECORDING_DURATION_SECONDS = 2;
export const MAX_RECORDING_DURATION_SECONDS = 45;
export const MAX_RECORDING_SIZE_BYTES = 12 * 1024 * 1024;
export const MIN_RECORDING_SIZE_BYTES = 512;
